name: Build and Deploy React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Directory Structure
        run: |
          pwd  # Print the current working directory to verify location
          ls -R  # List all files and directories to confirm paths

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        run: |
          # Create and use a new builder instance
          docker buildx create --use
          
          # Build and push the Docker image using the correct paths
          docker buildx build --platform linux/amd64 \
            -t bennassermedghassen/react-app:${{ github.sha }} \
            --push \
            --file "./frontend/FRONTENDQR/Dockerfile" \  # Correct Dockerfile path
            "./frontend/FRONTENDQR"                    # Correct build context
        shell: bash
